use bevy::prelude::*;

#[derive(Resource, Clone)]
pub struct GameAssets {
    pub font_title: Handle<Font>,
    pub font_body: Handle<Font>,
    pub font_hud: Handle<Font>,
    pub button: Handle<Image>,
    pub button_blue: Handle<Image>,
    pub button_green: Handle<Image>,
    pub button_yellow: Handle<Image>,
    pub button_red: Handle<Image>,
    pub button_pause: Handle<Image>,
    pub panel_glass: Handle<Image>,
    pub panel_pixel: Handle<Image>,
    pub banner: Handle<Image>,
    pub banner_wide: Handle<Image>,
    pub banner_hanging: Handle<Image>,
    pub banner_curtain: Handle<Image>,
    pub bar: Handle<Image>,
    pub icon_coin: Handle<Image>,
    pub icon_trophy: Handle<Image>,
    pub icon_star: Handle<Image>,
    pub icon_gear: Handle<Image>,
    pub icon_play: Handle<Image>,
    pub icon_home: Handle<Image>,
    pub icon_pause: Handle<Image>,
    pub icon_info: Handle<Image>,
    pub icon_heart: Handle<Image>,
    pub icon_heart_empty: Handle<Image>,
    pub icon_arrow_up: Handle<Image>,
    pub icon_arrow_down: Handle<Image>,
    pub icon_arrow_left: Handle<Image>,
    pub icon_arrow_right: Handle<Image>,
    pub icon_exclaim: Handle<Image>,
    pub icon_medal: Handle<Image>,
    pub icon_locked: Handle<Image>,
    pub icon_power: Handle<Image>,
    pub icon_board: Handle<Image>,
    pub icon_mouse: Handle<Image>,
    pub icon_dpad: Handle<Image>,
    pub icon_tilt: Handle<Image>,
    pub icon_repeat: Handle<Image>,
    pub icon_check: Handle<Image>,
    pub star_badge: Handle<Image>,
    pub key_up: Handle<Image>,
    pub key_down: Handle<Image>,
    pub key_left: Handle<Image>,
    pub key_right: Handle<Image>,
    pub key_space: Handle<Image>,
    pub key_esc: Handle<Image>,
    pub key_w: Handle<Image>,
    pub key_a: Handle<Image>,
    pub key_s: Handle<Image>,
    pub key_d: Handle<Image>,
    pub coin: Handle<Image>,
    pub coin_silver: Handle<Image>,
    pub coin_bronze: Handle<Image>,
    pub coin_side: Handle<Image>,
    pub crate_box: Handle<Image>,
    pub crate_warn: Handle<Image>,
    pub crate_boom: Handle<Image>,
    pub spikes: Handle<Image>,
    pub log: Handle<Image>,
    pub weight: Handle<Image>,
    pub chain: Handle<Image>,
    pub gem_blue: Handle<Image>,
    pub gem_green: Handle<Image>,
    pub gem_yellow: Handle<Image>,
    pub gem_red: Handle<Image>,
    pub world_star: Handle<Image>,
    pub roof: Handle<Image>,
    pub wall: Handle<Image>,
    pub lane_near: Handle<Image>,
    pub lane_mid: Handle<Image>,
    pub lane_far: Handle<Image>,
    pub bush: Handle<Image>,
    pub plant: Handle<Image>,
    pub plant_purple: Handle<Image>,
    pub rock: Handle<Image>,
    pub flag: Handle<Image>,
    pub cloud: Handle<Image>,
    pub torch: Handle<Image>,
    pub fence: Handle<Image>,
    pub sign: Handle<Image>,
    pub tower: Handle<Image>,
    pub castle: Handle<Image>,
    pub temple: Handle<Image>,
    pub tree: Handle<Image>,
    pub tree2: Handle<Image>,
    pub pyramid: Handle<Image>,
    pub mountain: Handle<Image>,
    pub hills: Handle<Image>,
    pub sign_arrow: Handle<Image>,
    pub fireball: Handle<Image>,
    pub bomb: Handle<Image>,
    pub saw: Handle<Image>,
    pub block_warn: Handle<Image>,
    pub block_exclaim: Handle<Image>,
    pub flag_red: Handle<Image>,
    pub flag_yellow: Handle<Image>,
    pub cactus: Handle<Image>,
    pub torch_on: Handle<Image>,
    pub torch_on2: Handle<Image>,
    pub particle_star: Handle<Image>,
    pub particle_circle: Handle<Image>,
    pub particle_spark: Handle<Image>,
    pub dust: Handle<Image>,
    pub dust2: Handle<Image>,
}

impl GameAssets {
    pub fn coin_frame(&self, frame: usize) -> Handle<Image> {
        match frame % 4 {
            0 => self.coin.clone(),
            1 => self.coin_side.clone(),
            2 => self.coin_silver.clone(),
            _ => self.coin_bronze.clone(),
        }
    }

    pub fn power_icon(&self, kind: fuzzy_runner::PowerUpKind) -> Handle<Image> {
        match kind {
            fuzzy_runner::PowerUpKind::Magnet => self.gem_blue.clone(),
            fuzzy_runner::PowerUpKind::Shield => self.gem_green.clone(),
            fuzzy_runner::PowerUpKind::Multiplier => self.gem_yellow.clone(),
            fuzzy_runner::PowerUpKind::Boost => self.gem_red.clone(),
        }
    }
}

pub struct AssetsPlugin;

impl Plugin for AssetsPlugin {
    fn build(&self, app: &mut App) {
        app.add_systems(PreStartup, load_game_assets);
    }
}

fn load_game_assets(mut commands: Commands, asset_server: Res<AssetServer>) {
    commands.insert_resource(GameAssets {
        font_title: asset_server.load("fonts/Orbitron-Bold.ttf"),
        font_body: asset_server.load("fonts/KenneyFutureNarrow.ttf"),
        font_hud: asset_server.load("fonts/KenneyMini.ttf"),
        button: asset_server.load("ui/button.png"),
        button_blue: asset_server.load("ui/button_blue.png"),
        button_green: asset_server.load("ui/button_green.png"),
        button_yellow: asset_server.load("ui/button_yellow.png"),
        button_red: asset_server.load("ui/button_red.png"),
        button_pause: asset_server.load("ui/button_pause.png"),
        panel_glass: asset_server.load("ui/panel_glass.png"),
        panel_pixel: asset_server.load("ui/panel_pixel.png"),
        banner: asset_server.load("ui/banner.png"),
        banner_wide: asset_server.load("ui/banner_wide.png"),
        banner_hanging: asset_server.load("ui/banner_hanging.png"),
        banner_curtain: asset_server.load("ui/banner_curtain.png"),
        bar: asset_server.load("ui/bar.png"),
        icon_coin: asset_server.load("icons/hud_coin.png"),
        icon_trophy: asset_server.load("icons/trophy.png"),
        icon_star: asset_server.load("icons/star.png"),
        icon_gear: asset_server.load("icons/gear.png"),
        icon_play: asset_server.load("icons/play.png"),
        icon_home: asset_server.load("icons/home.png"),
        icon_pause: asset_server.load("icons/pause.png"),
        icon_info: asset_server.load("icons/info.png"),
        icon_heart: asset_server.load("icons/heart.png"),
        icon_heart_empty: asset_server.load("icons/heart_empty.png"),
        icon_arrow_up: asset_server.load("icons/arrow_up.png"),
        icon_arrow_down: asset_server.load("icons/arrow_down.png"),
        icon_arrow_left: asset_server.load("icons/arrow_left.png"),
        icon_arrow_right: asset_server.load("icons/arrow_right.png"),
        icon_exclaim: asset_server.load("icons/exclaim.png"),
        icon_medal: asset_server.load("icons/medal.png"),
        icon_locked: asset_server.load("icons/locked.png"),
        icon_power: asset_server.load("icons/power.png"),
        icon_board: asset_server.load("icons/board.png"),
        icon_mouse: asset_server.load("icons/mouse.png"),
        icon_dpad: asset_server.load("icons/dpad.png"),
        icon_tilt: asset_server.load("icons/tilt.png"),
        icon_repeat: asset_server.load("icons/repeat.png"),
        icon_check: asset_server.load("ui/check.png"),
        star_badge: asset_server.load("ui/star_badge.png"),
        key_up: asset_server.load("prompts/key_up.png"),
        key_down: asset_server.load("prompts/key_down.png"),
        key_left: asset_server.load("prompts/key_left.png"),
        key_right: asset_server.load("prompts/key_right.png"),
        key_space: asset_server.load("prompts/key_space.png"),
        key_esc: asset_server.load("prompts/key_esc.png"),
        key_w: asset_server.load("prompts/key_w.png"),
        key_a: asset_server.load("prompts/key_a.png"),
        key_s: asset_server.load("prompts/key_s.png"),
        key_d: asset_server.load("prompts/key_d.png"),
        coin: asset_server.load("world/coin.png"),
        coin_silver: asset_server.load("world/coin_silver.png"),
        coin_bronze: asset_server.load("world/coin_bronze.png"),
        coin_side: asset_server.load("world/coin_side.png"),
        crate_box: asset_server.load("world/crate.png"),
        crate_warn: asset_server.load("world/crate_warning.png"),
        crate_boom: asset_server.load("world/crate_explosive.png"),
        spikes: asset_server.load("world/spikes.png"),
        log: asset_server.load("world/log.png"),
        weight: asset_server.load("world/weight.png"),
        chain: asset_server.load("world/chain.png"),
        gem_blue: asset_server.load("world/gem_blue.png"),
        gem_green: asset_server.load("world/gem_green.png"),
        gem_yellow: asset_server.load("world/gem_yellow.png"),
        gem_red: asset_server.load("world/gem_red.png"),
        world_star: asset_server.load("world/star.png"),
        roof: asset_server.load("world/roof.png"),
        wall: asset_server.load("world/wall.png"),
        lane_near: asset_server.load("world/lane_near.png"),
        lane_mid: asset_server.load("world/lane_mid.png"),
        lane_far: asset_server.load("world/lane_far.png"),
        bush: asset_server.load("world/bush.png"),
        plant: asset_server.load("world/plant.png"),
        plant_purple: asset_server.load("world/plant_purple.png"),
        rock: asset_server.load("world/rock.png"),
        flag: asset_server.load("world/flag.png"),
        cloud: asset_server.load("world/cloud.png"),
        torch: asset_server.load("world/torch.png"),
        fence: asset_server.load("world/fence.png"),
        sign: asset_server.load("world/sign.png"),
        tower: asset_server.load("world/tower.png"),
        castle: asset_server.load("world/castle.png"),
        temple: asset_server.load("world/temple.png"),
        tree: asset_server.load("world/tree.png"),
        tree2: asset_server.load("world/tree2.png"),
        pyramid: asset_server.load("world/pyramid.png"),
        mountain: asset_server.load("world/mountain.png"),
        hills: asset_server.load("world/hills.png"),
        sign_arrow: asset_server.load("world/sign_arrow.png"),
        fireball: asset_server.load("world/fireball.png"),
        bomb: asset_server.load("world/bomb.png"),
        saw: asset_server.load("world/saw.png"),
        block_warn: asset_server.load("world/block_warn.png"),
        block_exclaim: asset_server.load("world/block_exclaim.png"),
        flag_red: asset_server.load("world/flag_red.png"),
        flag_yellow: asset_server.load("world/flag_yellow.png"),
        cactus: asset_server.load("world/cactus.png"),
        torch_on: asset_server.load("world/torch_on.png"),
        torch_on2: asset_server.load("world/torch_on2.png"),
        particle_star: asset_server.load("particles/star.png"),
        particle_circle: asset_server.load("particles/circle.png"),
        particle_spark: asset_server.load("particles/spark.png"),
        dust: asset_server.load("particles/dust.png"),
        dust2: asset_server.load("particles/dust2.png"),
    });
}
